/* Plugin A 表单初始值、选项与字段文案。静态配置集中维护，页面逻辑不再承载数据字典。 */

export const initialForm: Record<string, any> = {
  pcbName: "", pcbFile: "", layerCount: null, blindVia: false,
  pcsSizeWidth: null, pcsSizeHeight: null, dimensionTolerance: 0.1, quantity: 10, deliveryUnit: "PCS",
  panelTypesCount: 1, setMethod: "单片无拼板", clientPanelHorizontal: 1, clientPanelVertical: 1,
  setSizeWidth: null, setSizeHeight: null, clientPanelSeparation: "拼板+V-CUT交货", acceptXOut: false,
  materialType: "FR4", materialBrand: "", materialVersion: "", materialTg: true, halogenFree: false,
  maxWarpage: "0.75%", boardThickness: null, thicknessTolerance: "+/-10%",
  outerCopperThickness: 35, outerBaseCopperThickness: 18, innerCopperThickness: 1,
  minTraceWidthOuter: 20, minTraceSpacingOuter: 20, minTraceWidthInner: 20, minTraceSpacingInner: 20,
  minHoleSize: 0.200, throughHoleQty: null, holeCopperThickness: 18, solderMaskColor: "绿色", silkscreenColor: "白色字符",
  surfaceFinish: "无铅喷锡", enigGoldThickness: 0.0508, immersionGoldArea: 20.0,
  viaProcess: "阻焊塞孔", goldFingerType: "无", goldFingerThickness: 0.381,
  goldFingerChamferAngle: "30°", goldFingerChamferDepth: 0.50, goldFingerChamferRemaining: 0.60,
  acceptanceStandard: "IPC 2", impedanceControl: false,
  markingRequirements: ["不需要"] as string[], periodFormat: "WWYY",
  testRequirements: ["飞针测试"] as string[], shippingReports: ["最终产品检查报告"] as string[], specialProcesses: ["不需要"] as string[],
  confirmProductionFile: false,
  remark: [] as string[],
}

export const defaultValues: Record<string, any> = JSON.parse(JSON.stringify({
  pcbName: "", pcbFile: "", layerCount: null, blindVia: false,
  pcsSizeWidth: null, pcsSizeHeight: null, dimensionTolerance: 0.1, quantity: 10, deliveryUnit: "PCS",
  panelTypesCount: 1, setMethod: "单片无拼板", clientPanelHorizontal: 1, clientPanelVertical: 1,
  setSizeWidth: null, setSizeHeight: null, clientPanelSeparation: "拼板+V-CUT交货", acceptXOut: false,
  materialType: "FR4", materialBrand: "", materialVersion: "", materialTg: true, halogenFree: false,
  maxWarpage: "0.75%", boardThickness: null, thicknessTolerance: "+/-10%",
  outerCopperThickness: 35, outerBaseCopperThickness: 18, innerCopperThickness: 1,
  minTraceWidthOuter: 20, minTraceSpacingOuter: 20, minTraceWidthInner: 20, minTraceSpacingInner: 20,
  minHoleSize: 0.200, throughHoleQty: null, holeCopperThickness: 18, solderMaskColor: "绿色", silkscreenColor: "白色字符",
  surfaceFinish: "无铅喷锡", enigGoldThickness: 0.0508, immersionGoldArea: 20.0,
  viaProcess: "阻焊塞孔", goldFingerType: "无", goldFingerThickness: 0.381,
  goldFingerChamferAngle: "30°", goldFingerChamferDepth: 0.50, goldFingerChamferRemaining: 0.60,
  acceptanceStandard: "IPC 2", impedanceControl: false,
  markingRequirements: ["不需要"], periodFormat: "WWYY",
  testRequirements: ["飞针测试"], shippingReports: ["最终产品检查报告"], specialProcesses: ["不需要"],
  confirmProductionFile: false,
}))

export const formOptions: Record<string, any[]> = {
  layerCount: ["1","2","4","6","8","10","12","14","16","18","20","22","24","26","28","30"],
  blindVia: [{ value: false, label: '否' }, { value: true, label: '是' }],
  deliveryUnit: ["PCS","SET"], setMethodAll: ["单片无拼板","单片加工艺边","客户拼板"],
  clientPanelSeparation: ["拼板&邮票孔交货","拼板铣开交货","拼板V-CUT+桥连交货","拼板桥连+邮票孔","拼板V-CUT+邮票孔","拼板V-CUT桥连+邮票孔","拼板桥连交货","拼板+V-CUT交货"],
  acceptXOut: [{ value: true, label: '是' }, { value: false, label: '否' }],
  materialType: ["FR4","高速板材","高频板","PTFE板材","PI"],
  materialBrand: ["生益","联茂","建滔","华正","超声","松下","Isola","台光","台耀","南亚","Rogers","其它"],
  materialVersion: ["IT-158","NY2150","S1000H","IT-180A","TU-752","S1000-2M","RO4350B","RO4350","RO4003C","FR408HR","S7439","IT-968","IT-958G"],
  materialTg: [{ value: false, label: '否' }, { value: true, label: '是' }],
  halogenFree: [{ value: false, label: '否' }, { value: true, label: '是' }],
  maxWarpage: ["无要求","0.75%","0.5%","IPC标准"],
  boardThickness: ["0.2","0.3","0.4","0.5","0.6","0.7","0.8","0.9","1.0","1.1","1.2","1.3","1.4","1.5","1.6","1.7","1.8","1.9","2.0","2.1","2.2","2.3","2.4","2.5","2.6","2.7","2.8","2.9","3.0","3.1","3.2","3.3","3.4","3.5","3.6","3.7","3.8","3.9","4.0","4.1","4.2","4.3","4.4","4.5","4.6","4.7","4.8","4.9","5.0","5.1","5.2","5.3","5.4","5.5","5.6","5.7","5.8","5.9","6.0"],
  thicknessTolerance: ["+/-10%","+/-0.10mm"],
  outerCopperThickness: ["35","70","105","140","175","210"],
  outerBaseCopperThickness: ["8","12","18","35","52.5","70","105","140","175","210"],
  innerCopperThickness: ["0.5","1","2","3","4","5","6"],
  holeCopperThickness: ["18","20","25","25.4","30","35","40","45","50"],
  solderMaskColor: ["绿色","绿色亚光","黑色","黑色亚光","蓝色","红色","不印阻焊"],
  silkscreenColor: ["白色字符","黑色字符","不印字符"],
  surfaceFinish: ["沉金","无铅喷锡","OSP","喷锡","沉银","沉锡","无需表面处理"],
  enigGoldThickness: ["0.0508","0.0762","0.080","0.1016"],
  viaProcess: ["按Gerber文件","阻焊覆盖","BGA芯片处阻焊塞孔+按Gerber文件","不盖阻焊","阻焊塞孔","非导电树脂塞孔","非导电树脂塞孔+电镀填平"],
  goldFingerType: ["无","常规金手指","分段金手指","长短金手指"],
  goldFingerThickness: ["0.381","0.762","0.8","1.25"],
  goldFingerChamferAngle: ["20°","30°","45°","不倒角"],
  acceptanceStandard: ["IPC 2","IPC 3"],
  impedanceControl: [{ value: false, label: '否' }, { value: true, label: '是' }],
  markingRequirements: ["PCB厂家标记","周期标记","无铅标记","rosh标记","防静电标记","加拿大UL","不需要"],
  periodFormat: ["WWYY","YYWW","MMYY","YYMM","DDMMYY","YYMMDD"],
  testRequirements: ["电感测试","损耗","耐电压测试","孔电阻测试","线电阻测试","不需要","飞针测试","夹具测试"],
  shippingReports: ["最终产品检查报告","回流焊测试报告","可焊性测试报告","离子污染度测试报告","耐电压测试报告","热应力检测报告","不需要"],
  specialProcesses: ["电镀填孔","金属包边","金属化半孔","背钻孔","锥形孔","阶梯孔","铣阶梯槽","控深钻","不需要"],
  confirmProductionFile: [{ value: false, label: '否' }, { value: true, label: '是' }],
}

export const fieldLabels: Record<string, string> = {
  pcbFile: 'PCB资料', layerCount: '板子层数', pcsSizeWidth: 'PCS尺寸(水平)', pcsSizeHeight: 'PCS尺寸(垂直)',
  dimensionTolerance: '外形公差', quantity: '板子数量', deliveryUnit: '交货单位', panelTypesCount: '合拼种数', setMethod: 'Set拼板方式',
  materialType: '板材种类', materialTg: 'TG值', halogenFree: '无卤板材', maxWarpage: '翘曲度',
  boardThickness: '成品板厚', thicknessTolerance: '板厚公差', outerCopperThickness: '外层完成铜厚度', innerCopperThickness: '内层基铜厚度',
  minTraceWidthOuter: '外层最小线宽', minTraceSpacingOuter: '外层最小线距', minTraceWidthInner: '内层最小线宽', minTraceSpacingInner: '内层最小线距',
  minHoleSize: '最小孔径', holeCopperThickness: '最小孔铜', solderMaskColor: '阻焊颜色', silkscreenColor: '字符颜色', surfaceFinish: '表面处理',
  viaProcess: '过孔工艺', goldFingerType: '金手指类型', acceptanceStandard: '验收标准', impedanceControl: '阻抗控制',
  markingRequirements: '标记要求', testRequirements: '测试要求', shippingReports: '出货报告', specialProcesses: '特殊工艺', confirmProductionFile: '光绘确认',
  clientPanelHorizontal: '拼板个数(水平)', clientPanelVertical: '拼板个数(垂直)',
  setSizeWidth: 'Set尺寸(水平)', setSizeHeight: 'Set尺寸(垂直)', clientPanelSeparation: '外形要求',
  enigGoldThickness: '最小沉金金厚', immersionGoldArea: '沉金面积',
  goldFingerThickness: '金手指金厚', goldFingerChamferAngle: '倒角角度', periodFormat: '周期格式',
}
