server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # SPA 路由回退
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    # 代理：前端调 /proxy/xxx → nginx 转发到 https://aishop.elecnest.cn/xxx
    location /proxy/ {
        proxy_pass https://aishop.elecnest.cn/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # pdfjs 静态资源缓存
    location /pdfjs {
        expires 7d;
    }
}
