<script setup lang="ts">
import { ElAutocomplete, ElButton, ElInput, ElInputNumber, ElOption, ElSelect } from 'element-plus'

const props = defineProps<{ context: Record<string, any> }>()
const {
  form, sections, opts, fieldBgClass, sourceClass, sourceLabel, showGraphicBtn, showDocBtn, handleViewClick,
  queryLayerCount, onLayerCountBlur, requestPCSSize, requestSetSize, handleSizeBlur, requireClientPanelSeparation,
  onMaterialTypeChange, onMaterialBrandSelect, onMaterialBrandChange, queryMaterialBrand,
  onMaterialVersionSelect, onMaterialVersionChange, queryMaterialVersion, onMaterialTgChange, onMaterialHalogenChange,
  queryMaxWarpage, queryBoardThickness, queryThicknessTolerance, queryOuterCopperThickness,
  queryOuterBaseCopperThickness, queryInnerCopperThickness, hasInnerLayer, showEnigGold,
  queryEnigGoldThickness, queryHoleCopperThickness, showGoldFinger, queryGoldFingerThickness,
} = props.context
</script>

<template>
<!-- 一、基本信息 -->
          <tr class="section-row" @click="sections.basic = !sections.basic"><td colspan="4">一、PCB 基本信息 <span class="arrow" :class="{ up: sections.basic }">▼</span></td></tr>
          <template v-if="sections.basic">
            <tr style="display:none"><td>生产型号</td><td><el-input v-model="form.pcbName" size="large" /></td><td class="td-src"><span :class="sourceClass('pcbName')">{{ sourceLabel('pcbName') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('pcbName')" class="btn-view graphic" @click="handleViewClick('pcbName')">图形</button><button v-if="showDocBtn('pcbName')" class="btn-view doc" @click="handleViewClick('pcbName')">加工文档</button></td></tr>
            <tr><td>PCB 资料（客户品名）<span class="req">*</span></td><td :class="fieldBgClass('pcbFile')"><el-input v-model="form.pcbFile" size="large" /></td><td class="td-src"><span :class="sourceClass('pcbFile')">{{ sourceLabel('pcbFile') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('pcbFile')" class="btn-view graphic" @click="handleViewClick('pcbFile')">图形</button><button v-if="showDocBtn('pcbFile')" class="btn-view doc" @click="handleViewClick('pcbFile')">加工文档</button></td></tr>
            <tr><td>板子层数<span class="req">*</span></td><td :class="fieldBgClass('layerCount')"><el-autocomplete v-model="form.layerCount" :fetch-suggestions="queryLayerCount" size="large" style="width:100%" placeholder="输入板子层数" clearable @blur="onLayerCountBlur"><template #default="{ item }"><div class="autocomplete-item">{{ item.value }}</div></template></el-autocomplete><span class="unit">层</span></td><td class="td-src"><span :class="sourceClass('layerCount')">{{ sourceLabel('layerCount') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('layerCount')" class="btn-view graphic" @click="handleViewClick('layerCount')">图形</button><button v-if="showDocBtn('layerCount')" class="btn-view doc" @click="handleViewClick('layerCount')">加工文档</button></td></tr>
            <tr><td>盲埋孔</td><td :class="fieldBgClass('blindVia')"><el-select v-model="form.blindVia" size="large" style="width:100%"><el-option v-for="v in opts.blindVia" :key="v.value" :label="v.label" :value="v.value" /></el-select></td><td class="td-src"><span :class="sourceClass('blindVia')">{{ sourceLabel('blindVia') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('blindVia')" class="btn-view graphic" @click="handleViewClick('blindVia')">图形</button><button v-if="showDocBtn('blindVia')" class="btn-view doc" @click="handleViewClick('blindVia')">加工文档</button></td></tr>
            <tr><td>PCS尺寸(水平)<span class="req">*</span> <el-button type="primary" @click="requestPCSSize">获取尺寸</el-button></td><td :class="fieldBgClass('pcsSizeWidth')"><el-input-number :controls="false" v-model="form.pcsSizeWidth" :min="0" :precision="2" size="large" style="width:100%" @blur="handleSizeBlur" /><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('pcsSizeWidth')">{{ sourceLabel('pcsSizeWidth') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('pcsSizeWidth')" class="btn-view graphic" @click="handleViewClick('pcsSizeWidth')">图形</button><button v-if="showDocBtn('pcsSizeWidth')" class="btn-view doc" @click="handleViewClick('pcsSizeWidth')">加工文档</button></td></tr>
            <tr><td>PCS尺寸(垂直)<span class="req">*</span></td><td :class="fieldBgClass('pcsSizeHeight')"><el-input-number :controls="false" v-model="form.pcsSizeHeight" :min="0" :precision="2" size="large" style="width:100%" @blur="handleSizeBlur" /><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('pcsSizeHeight')">{{ sourceLabel('pcsSizeHeight') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('pcsSizeHeight')" class="btn-view graphic" @click="handleViewClick('pcsSizeHeight')">图形</button><button v-if="showDocBtn('pcsSizeHeight')" class="btn-view doc" @click="handleViewClick('pcsSizeHeight')">加工文档</button></td></tr>
            <tr><td>外形公差<span class="req">*</span></td><td :class="fieldBgClass('dimensionTolerance')"><span style="flex-shrink:0;color:#666">+/-</span><el-input-number :controls="false" v-model="form.dimensionTolerance" :min="0" :precision="2" :step="0.05" size="large" style="width:100%" /><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('dimensionTolerance')">{{ sourceLabel('dimensionTolerance') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('dimensionTolerance')" class="btn-view graphic" @click="handleViewClick('dimensionTolerance')">图形</button><button v-if="showDocBtn('dimensionTolerance')" class="btn-view doc" @click="handleViewClick('dimensionTolerance')">加工文档</button></td></tr>
            <tr><td>板子数量<span class="req">*</span></td><td :class="fieldBgClass('quantity')"><el-input-number :controls="false" v-model="form.quantity" :min="1" size="large" style="width:100%" /></td><td class="td-src"><span :class="sourceClass('quantity')">{{ sourceLabel('quantity') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('quantity')" class="btn-view graphic" @click="handleViewClick('quantity')">图形</button><button v-if="showDocBtn('quantity')" class="btn-view doc" @click="handleViewClick('quantity')">加工文档</button></td></tr>
            <tr><td>交货单位<span class="req">*</span></td><td :class="fieldBgClass('deliveryUnit')"><el-select v-model="form.deliveryUnit" size="large" style="width:100%"><el-option v-for="v in opts.deliveryUnit" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('deliveryUnit')">{{ sourceLabel('deliveryUnit') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('deliveryUnit')" class="btn-view graphic" @click="handleViewClick('deliveryUnit')">图形</button><button v-if="showDocBtn('deliveryUnit')" class="btn-view doc" @click="handleViewClick('deliveryUnit')">加工文档</button></td></tr>
            <tr><td>合拼种数<span class="req">*</span></td><td :class="fieldBgClass('panelTypesCount')"><el-input-number :controls="false" v-model="form.panelTypesCount" :min="1" :max="100" size="large" style="width:100%" /></td><td class="td-src"><span :class="sourceClass('panelTypesCount')">{{ sourceLabel('panelTypesCount') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('panelTypesCount')" class="btn-view graphic" @click="handleViewClick('panelTypesCount')">图形</button><button v-if="showDocBtn('panelTypesCount')" class="btn-view doc" @click="handleViewClick('panelTypesCount')">加工文档</button></td></tr>
            <tr><td>Set拼板方式<span class="req">*</span></td><td :class="fieldBgClass('setMethod')"><el-select v-model="form.setMethod" size="large" style="width:100%"><el-option v-for="v in opts.setMethodAll" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('setMethod')">{{ sourceLabel('setMethod') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('setMethod')" class="btn-view graphic" @click="handleViewClick('setMethod')">图形</button><button v-if="showDocBtn('setMethod')" class="btn-view doc" @click="handleViewClick('setMethod')">加工文档</button></td></tr>
              <tr><td>拼板个数(水平)<span class="req">*</span></td><td :class="fieldBgClass('clientPanelHorizontal')"><el-input-number :controls="false" v-model="form.clientPanelHorizontal" :min="1" :max="500" size="large" style="width:100%" /></td><td class="td-src"><span :class="sourceClass('clientPanelHorizontal')">{{ sourceLabel('clientPanelHorizontal') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('clientPanelHorizontal')" class="btn-view graphic" @click="handleViewClick('clientPanelHorizontal')">图形</button><button v-if="showDocBtn('clientPanelHorizontal')" class="btn-view doc" @click="handleViewClick('clientPanelHorizontal')">加工文档</button></td></tr>
              <tr><td>拼板个数(垂直)<span class="req">*</span></td><td :class="fieldBgClass('clientPanelVertical')"><el-input-number :controls="false" v-model="form.clientPanelVertical" :min="1" :max="500" size="large" style="width:100%" /></td><td class="td-src"><span :class="sourceClass('clientPanelVertical')">{{ sourceLabel('clientPanelVertical') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('clientPanelVertical')" class="btn-view graphic" @click="handleViewClick('clientPanelVertical')">图形</button><button v-if="showDocBtn('clientPanelVertical')" class="btn-view doc" @click="handleViewClick('clientPanelVertical')">加工文档</button></td></tr>
              <tr><td>Set尺寸(水平)<span class="req">*</span> <el-button type="primary" @click="requestSetSize">获取尺寸</el-button></td><td :class="fieldBgClass('setSizeWidth')"><el-input-number :controls="false" v-model="form.setSizeWidth" :min="0" :precision="2" size="large" style="width:100%" @blur="handleSizeBlur" /><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('setSizeWidth')">{{ sourceLabel('setSizeWidth') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('setSizeWidth')" class="btn-view graphic" @click="handleViewClick('setSizeWidth')">图形</button><button v-if="showDocBtn('setSizeWidth')" class="btn-view doc" @click="handleViewClick('setSizeWidth')">加工文档</button></td></tr>
              <tr><td>Set尺寸(垂直)<span class="req">*</span></td><td :class="fieldBgClass('setSizeHeight')"><el-input-number :controls="false" v-model="form.setSizeHeight" :min="0" :precision="2" size="large" style="width:100%" @blur="handleSizeBlur" /><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('setSizeHeight')">{{ sourceLabel('setSizeHeight') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('setSizeHeight')" class="btn-view graphic" @click="handleViewClick('setSizeHeight')">图形</button><button v-if="showDocBtn('setSizeHeight')" class="btn-view doc" @click="handleViewClick('setSizeHeight')">加工文档</button></td></tr>
              <tr v-if="requireClientPanelSeparation"><td>外形要求<span class="req">*</span></td><td :class="fieldBgClass('clientPanelSeparation')"><el-select v-model="form.clientPanelSeparation" placeholder=" " size="large" style="width:100%"><el-option v-for="v in opts.clientPanelSeparation" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('clientPanelSeparation')">{{ sourceLabel('clientPanelSeparation') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('clientPanelSeparation')" class="btn-view graphic" @click="handleViewClick('clientPanelSeparation')">图形</button><button v-if="showDocBtn('clientPanelSeparation')" class="btn-view doc" @click="handleViewClick('clientPanelSeparation')">加工文档</button></td></tr>
              <tr><td>是否接受打叉板</td><td :class="fieldBgClass('acceptXOut')"><el-select v-model="form.acceptXOut" size="large" style="width:100%"><el-option v-for="v in opts.acceptXOut" :key="v.value" :label="v.label" :value="v.value" /></el-select></td><td class="td-src"><span :class="sourceClass('acceptXOut')">{{ sourceLabel('acceptXOut') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('acceptXOut')" class="btn-view graphic" @click="handleViewClick('acceptXOut')">图形</button><button v-if="showDocBtn('acceptXOut')" class="btn-view doc" @click="handleViewClick('acceptXOut')">加工文档</button></td></tr>
          </template>
</template>

