<script setup lang="ts">
import { ElAutocomplete, ElButton, ElInput, ElInputNumber, ElOption, ElSelect } from 'element-plus'

const props = defineProps<{ context: Record<string, any> }>()
const {
  form, sections, opts, fieldBgClass, sourceClass, sourceLabel, showGraphicBtn, showDocBtn, handleViewClick,
  queryLayerCount, onLayerCountBlur, requestPCSSize, requestSetSize, handleSizeBlur, requireClientPanelSeparation,
  onMaterialTypeChange, onMaterialBrandSelect, onMaterialBrandChange, queryMaterialBrand,
  onMaterialVersionSelect, onMaterialVersionChange, queryMaterialVersion, onMaterialTgChange, onMaterialHalogenChange,
  queryMaxWarpage, queryBoardThickness, queryThicknessTolerance, queryOuterCopperThickness,
  queryOuterBaseCopperThickness, queryInnerCopperThickness, hasInnerLayer, showEnigGold,
  queryEnigGoldThickness, queryHoleCopperThickness, showGoldFinger, queryGoldFingerThickness,
  computedDrillDensity,
} = props.context
</script>

<template>
<!-- 二、工艺信息 -->
          <tr class="section-row" @click="sections.process = !sections.process"><td colspan="4">二、PCB 工艺信息 <span class="arrow" :class="{ up: sections.process }">▼</span></td></tr>
          <template v-if="sections.process">
            <tr><td>板材种类<span class="req">*</span></td><td :class="fieldBgClass('materialType')"><el-select v-model="form.materialType" @change="onMaterialTypeChange" size="large" style="width:100%"><el-option v-for="v in opts.materialType" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('materialType')">{{ sourceLabel('materialType') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('materialType')" class="btn-view graphic" @click="handleViewClick('materialType')">图形</button><button v-if="showDocBtn('materialType')" class="btn-view doc" @click="handleViewClick('materialType')">加工文档</button></td></tr>
            <tr><td>板材品牌</td><td :class="fieldBgClass('materialBrand')"><el-autocomplete v-model="form.materialBrand" @select="onMaterialBrandSelect" @change="onMaterialBrandChange" :fetch-suggestions="queryMaterialBrand" size="large" style="width:100%" placeholder="输入搜索板材品牌" clearable><template #default="{ item }"><div class="autocomplete-item">{{ item.value }}</div></template></el-autocomplete></td><td class="td-src"><span :class="sourceClass('materialBrand')">{{ sourceLabel('materialBrand') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('materialBrand')" class="btn-view graphic" @click="handleViewClick('materialBrand')">图形</button><button v-if="showDocBtn('materialBrand')" class="btn-view doc" @click="handleViewClick('materialBrand')">加工文档</button></td></tr>
            <tr><td>板材型号</td><td :class="fieldBgClass('materialVersion')"><el-autocomplete v-model="form.materialVersion" @select="onMaterialVersionSelect" @change="onMaterialVersionChange" :fetch-suggestions="queryMaterialVersion" size="large" style="width:100%" placeholder="输入搜索板材型号" clearable><template #default="{ item }"><div class="autocomplete-item">{{ item.value }}</div></template></el-autocomplete></td><td class="td-src"><span :class="sourceClass('materialVersion')">{{ sourceLabel('materialVersion') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('materialVersion')" class="btn-view graphic" @click="handleViewClick('materialVersion')">图形</button><button v-if="showDocBtn('materialVersion')" class="btn-view doc" @click="handleViewClick('materialVersion')">加工文档</button></td></tr>
            <tr><td>TG值<span class="req">*</span></td><td :class="fieldBgClass('materialTg')"><el-select v-model="form.materialTg" @change="onMaterialTgChange" size="large" style="width:100%"><el-option v-for="v in opts.materialTg" :key="v.value" :label="v.label" :value="v.value" /></el-select></td><td class="td-src"><span :class="sourceClass('materialTg')">{{ sourceLabel('materialTg') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('materialTg')" class="btn-view graphic" @click="handleViewClick('materialTg')">图形</button><button v-if="showDocBtn('materialTg')" class="btn-view doc" @click="handleViewClick('materialTg')">加工文档</button></td></tr>
            <tr><td>无卤板材<span class="req">*</span></td><td :class="fieldBgClass('halogenFree')"><el-select v-model="form.halogenFree" @change="onMaterialHalogenChange" size="large" style="width:100%"><el-option v-for="v in opts.halogenFree" :key="v.value" :label="v.label" :value="v.value" /></el-select></td><td class="td-src"><span :class="sourceClass('halogenFree')">{{ sourceLabel('halogenFree') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('halogenFree')" class="btn-view graphic" @click="handleViewClick('halogenFree')">图形</button><button v-if="showDocBtn('halogenFree')" class="btn-view doc" @click="handleViewClick('halogenFree')">加工文档</button></td></tr>
            <tr><td>翘曲度<span class="req">*</span></td><td :class="fieldBgClass('maxWarpage')"><el-autocomplete v-model="form.maxWarpage" :fetch-suggestions="queryMaxWarpage" size="large" style="width:100%" placeholder="输入搜索翘曲度" clearable><template #default="{ item }"><div class="autocomplete-item">{{ item.value }}</div></template></el-autocomplete></td><td class="td-src"><span :class="sourceClass('maxWarpage')">{{ sourceLabel('maxWarpage') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('maxWarpage')" class="btn-view graphic" @click="handleViewClick('maxWarpage')">图形</button><button v-if="showDocBtn('maxWarpage')" class="btn-view doc" @click="handleViewClick('maxWarpage')">加工文档</button></td></tr>
            <tr><td>成品板厚<span class="req">*</span></td><td :class="fieldBgClass('boardThickness')"><el-autocomplete v-model="form.boardThickness" :fetch-suggestions="queryBoardThickness" @select="(item: any) => { form.boardThickness = item.value }" size="large" style="width:100%" placeholder="输入搜索成品板厚" clearable><template #default="{ item }"><div class="autocomplete-item">{{ item.value }}</div></template></el-autocomplete><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('boardThickness')">{{ sourceLabel('boardThickness') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('boardThickness')" class="btn-view graphic" @click="handleViewClick('boardThickness')">图形</button><button v-if="showDocBtn('boardThickness')" class="btn-view doc" @click="handleViewClick('boardThickness')">加工文档</button></td></tr>
            <tr><td>板厚公差<span class="req">*</span></td><td :class="fieldBgClass('thicknessTolerance')"><el-autocomplete v-model="form.thicknessTolerance" :fetch-suggestions="queryThicknessTolerance" size="large" style="width:100%" placeholder="格式如：+/-10mm 或 +/-10%" clearable><template #default="{ item }"><div class="autocomplete-item">{{ item.value }}</div></template></el-autocomplete></td><td class="td-src"><span :class="sourceClass('thicknessTolerance')">{{ sourceLabel('thicknessTolerance') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('thicknessTolerance')" class="btn-view graphic" @click="handleViewClick('thicknessTolerance')">图形</button><button v-if="showDocBtn('thicknessTolerance')" class="btn-view doc" @click="handleViewClick('thicknessTolerance')">加工文档</button></td></tr>
            <tr><td>外层完成铜厚度<span class="req">*</span></td><td :class="fieldBgClass('outerCopperThickness')"><el-autocomplete v-model="form.outerCopperThickness" :fetch-suggestions="queryOuterCopperThickness" @select="(item: any) => { form.outerCopperThickness = item.value }" size="large" style="width:100%" placeholder="输入搜索外层完成铜厚度" clearable><template #default="{ item }"><div class="autocomplete-item">{{ item.value }}</div></template></el-autocomplete><span class="unit">um</span></td><td class="td-src"><span :class="sourceClass('outerCopperThickness')">{{ sourceLabel('outerCopperThickness') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('outerCopperThickness')" class="btn-view graphic" @click="handleViewClick('outerCopperThickness')">图形</button><button v-if="showDocBtn('outerCopperThickness')" class="btn-view doc" @click="handleViewClick('outerCopperThickness')">加工文档</button></td></tr>
            <tr><td>外层基铜厚度</td><td :class="fieldBgClass('outerBaseCopperThickness')"><el-autocomplete v-model="form.outerBaseCopperThickness" :fetch-suggestions="queryOuterBaseCopperThickness" @select="(item: any) => { form.outerBaseCopperThickness = item.value }" size="large" style="width:100%" placeholder="输入搜索外层基铜厚度" clearable><template #default="{ item }"><div class="autocomplete-item">{{ item.value }}</div></template></el-autocomplete><span class="unit">um</span></td><td class="td-src"><span :class="sourceClass('outerBaseCopperThickness')">{{ sourceLabel('outerBaseCopperThickness') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('outerBaseCopperThickness')" class="btn-view graphic" @click="handleViewClick('outerBaseCopperThickness')">图形</button><button v-if="showDocBtn('outerBaseCopperThickness')" class="btn-view doc" @click="handleViewClick('outerBaseCopperThickness')">加工文档</button></td></tr>
            <template v-if="hasInnerLayer"><tr><td>内层基铜厚度<span class="req">*</span></td><td :class="fieldBgClass('innerCopperThickness')"><el-autocomplete v-model="form.innerCopperThickness" :fetch-suggestions="queryInnerCopperThickness" size="large" style="width:100%" placeholder="输入搜索内层基铜厚度" clearable @select="(item: any) => { form.innerCopperThickness = item.value }"><template #default="{ item }"><div class="autocomplete-item">{{ item.value }} oz</div></template></el-autocomplete><span class="unit">oz</span></td><td class="td-src"><span :class="sourceClass('innerCopperThickness')">{{ sourceLabel('innerCopperThickness') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('innerCopperThickness')" class="btn-view graphic" @click="handleViewClick('innerCopperThickness')">图形</button><button v-if="showDocBtn('innerCopperThickness')" class="btn-view doc" @click="handleViewClick('innerCopperThickness')">加工文档</button></td></tr></template>
            <tr><td>外层最小线宽<span class="req">*</span></td><td :class="fieldBgClass('minTraceWidthOuter')"><el-input-number :controls="false" v-model="form.minTraceWidthOuter" :min="0" :precision="2" size="large" style="width:100%" /><span class="unit">mil</span></td><td class="td-src"><span :class="sourceClass('minTraceWidthOuter')">{{ sourceLabel('minTraceWidthOuter') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('minTraceWidthOuter')" class="btn-view graphic" @click="handleViewClick('minTraceWidthOuter')">图形</button><button v-if="showDocBtn('minTraceWidthOuter')" class="btn-view doc" @click="handleViewClick('minTraceWidthOuter')">加工文档</button></td></tr>
            <tr><td>外层最小线距<span class="req">*</span></td><td :class="fieldBgClass('minTraceSpacingOuter')"><el-input-number :controls="false" v-model="form.minTraceSpacingOuter" :min="0" :precision="2" size="large" style="width:100%" /><span class="unit">mil</span></td><td class="td-src"><span :class="sourceClass('minTraceSpacingOuter')">{{ sourceLabel('minTraceSpacingOuter') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('minTraceSpacingOuter')" class="btn-view graphic" @click="handleViewClick('minTraceSpacingOuter')">图形</button><button v-if="showDocBtn('minTraceSpacingOuter')" class="btn-view doc" @click="handleViewClick('minTraceSpacingOuter')">加工文档</button></td></tr>
              <template v-if="hasInnerLayer">
              <tr><td>内层最小线宽<span class="req">*</span></td><td :class="fieldBgClass('minTraceWidthInner')"><el-input-number :controls="false" v-model="form.minTraceWidthInner" :min="0" :precision="2" size="large" style="width:100%" /><span class="unit">mil</span></td><td class="td-src"><span :class="sourceClass('minTraceWidthInner')">{{ sourceLabel('minTraceWidthInner') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('minTraceWidthInner')" class="btn-view graphic" @click="handleViewClick('minTraceWidthInner')">图形</button><button v-if="showDocBtn('minTraceWidthInner')" class="btn-view doc" @click="handleViewClick('minTraceWidthInner')">加工文档</button></td></tr>
              <tr><td>内层最小线距<span class="req">*</span></td><td :class="fieldBgClass('minTraceSpacingInner')"><el-input-number :controls="false" v-model="form.minTraceSpacingInner" :min="0" :precision="2" size="large" style="width:100%" /><span class="unit">mil</span></td><td class="td-src"><span :class="sourceClass('minTraceSpacingInner')">{{ sourceLabel('minTraceSpacingInner') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('minTraceSpacingInner')" class="btn-view graphic" @click="handleViewClick('minTraceSpacingInner')">图形</button><button v-if="showDocBtn('minTraceSpacingInner')" class="btn-view doc" @click="handleViewClick('minTraceSpacingInner')">加工文档</button></td></tr>
              </template>
            <tr><td>最小孔径<span class="req">*</span></td><td :class="fieldBgClass('minHoleSize')"><el-input-number :controls="false" v-model="form.minHoleSize" :min="0" :precision="3" size="large" style="width:100%" /><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('minHoleSize')">{{ sourceLabel('minHoleSize') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('minHoleSize')" class="btn-view graphic" @click="handleViewClick('minHoleSize')">图形</button><button v-if="showDocBtn('minHoleSize')" class="btn-view doc" @click="handleViewClick('minHoleSize')">加工文档</button></td></tr>
			            <tr><td>钻孔密度</td><td><span style="display:inline-block;padding:4px 8px;">{{ computedDrillDensity || '--' }}</span><span class="unit">万孔/平米</span></td><td class="td-src"><span class="badge ai">AI提参</span></td><td class="td-view"></td></tr>
			            <tr><td>通孔孔数/PCS</td><td :class="fieldBgClass('throughHoleQty')"><el-input-number :controls="false" v-model="form.throughHoleQty" :min="0" :precision="0" size="large" style="width:100%" /></td><td class="td-src"><span :class="sourceClass('throughHoleQty')">{{ sourceLabel('throughHoleQty') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('throughHoleQty')" class="btn-view graphic" @click="handleViewClick('throughHoleQty')">图形</button><button v-if="showDocBtn('throughHoleQty')" class="btn-view doc" @click="handleViewClick('throughHoleQty')">加工文档</button></td></tr>
            <tr><td>最小孔铜<span class="req">*</span></td><td :class="fieldBgClass('holeCopperThickness')"><el-autocomplete v-model="form.holeCopperThickness" :fetch-suggestions="queryHoleCopperThickness" size="large" style="width:100%" placeholder="输入或选择" clearable @select="(item: any) => { form.holeCopperThickness = item.value }"><template #default="{ item }"><div class="autocomplete-item">{{ item.value }} um</div></template></el-autocomplete><span class="unit">um</span></td><td class="td-src"><span :class="sourceClass('holeCopperThickness')">{{ sourceLabel('holeCopperThickness') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('holeCopperThickness')" class="btn-view graphic" @click="handleViewClick('holeCopperThickness')">图形</button><button v-if="showDocBtn('holeCopperThickness')" class="btn-view doc" @click="handleViewClick('holeCopperThickness')">加工文档</button></td></tr>
            <tr><td>阻焊颜色<span class="req">*</span></td><td :class="fieldBgClass('solderMaskColor')"><el-select v-model="form.solderMaskColor" size="large" style="width:100%"><el-option v-for="v in opts.solderMaskColor" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('solderMaskColor')">{{ sourceLabel('solderMaskColor') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('solderMaskColor')" class="btn-view graphic" @click="handleViewClick('solderMaskColor')">图形</button><button v-if="showDocBtn('solderMaskColor')" class="btn-view doc" @click="handleViewClick('solderMaskColor')">加工文档</button></td></tr>
            <tr><td>字符颜色<span class="req">*</span></td><td :class="fieldBgClass('silkscreenColor')"><el-select v-model="form.silkscreenColor" size="large" style="width:100%"><el-option v-for="v in opts.silkscreenColor" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('silkscreenColor')">{{ sourceLabel('silkscreenColor') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('silkscreenColor')" class="btn-view graphic" @click="handleViewClick('silkscreenColor')">图形</button><button v-if="showDocBtn('silkscreenColor')" class="btn-view doc" @click="handleViewClick('silkscreenColor')">加工文档</button></td></tr>
            <tr><td>表面处理<span class="req">*</span></td><td :class="fieldBgClass('surfaceFinish')"><el-select v-model="form.surfaceFinish" size="large" style="width:100%"><el-option v-for="v in opts.surfaceFinish" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('surfaceFinish')">{{ sourceLabel('surfaceFinish') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('surfaceFinish')" class="btn-view graphic" @click="handleViewClick('surfaceFinish')">图形</button><button v-if="showDocBtn('surfaceFinish')" class="btn-view doc" @click="handleViewClick('surfaceFinish')">加工文档</button></td></tr>
              <template v-if="showEnigGold">
              <tr><td>最小沉金金厚<span class="req">*</span></td><td :class="fieldBgClass('enigGoldThickness')"><el-autocomplete v-model="form.enigGoldThickness" :fetch-suggestions="queryEnigGoldThickness" size="large" style="width:100%" placeholder="输入搜索最小沉金金厚" clearable @select="(item: any) => { form.enigGoldThickness = item.value }"><template #default="{ item }"><div class="autocomplete-item">{{ item.value }} um</div></template></el-autocomplete><span class="unit">um</span></td><td class="td-src"><span :class="sourceClass('enigGoldThickness')">{{ sourceLabel('enigGoldThickness') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('enigGoldThickness')" class="btn-view graphic" @click="handleViewClick('enigGoldThickness')">图形</button><button v-if="showDocBtn('enigGoldThickness')" class="btn-view doc" @click="handleViewClick('enigGoldThickness')">加工文档</button></td></tr>
              <tr><td>沉金面积（双面之和）<span class="req">*</span></td><td :class="fieldBgClass('immersionGoldArea')"><el-input-number :controls="false" v-model="form.immersionGoldArea" :min="0" :precision="1" size="large" style="width:100%" /><span class="unit">%</span></td><td class="td-src"><span :class="sourceClass('immersionGoldArea')">{{ sourceLabel('immersionGoldArea') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('immersionGoldArea')" class="btn-view graphic" @click="handleViewClick('immersionGoldArea')">图形</button><button v-if="showDocBtn('immersionGoldArea')" class="btn-view doc" @click="handleViewClick('immersionGoldArea')">加工文档</button></td></tr>
              </template>
            <tr><td>过孔工艺<span class="req">*</span></td><td :class="fieldBgClass('viaProcess')"><el-select v-model="form.viaProcess" size="large" style="width:100%"><el-option v-for="v in opts.viaProcess" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('viaProcess')">{{ sourceLabel('viaProcess') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('viaProcess')" class="btn-view graphic" @click="handleViewClick('viaProcess')">图形</button><button v-if="showDocBtn('viaProcess')" class="btn-view doc" @click="handleViewClick('viaProcess')">加工文档</button></td></tr>
            <tr><td>金手指类型<span class="req">*</span></td><td :class="fieldBgClass('goldFingerType')"><el-select v-model="form.goldFingerType" size="large" style="width:100%"><el-option v-for="v in opts.goldFingerType" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('goldFingerType')">{{ sourceLabel('goldFingerType') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('goldFingerType')" class="btn-view graphic" @click="handleViewClick('goldFingerType')">图形</button><button v-if="showDocBtn('goldFingerType')" class="btn-view doc" @click="handleViewClick('goldFingerType')">加工文档</button></td></tr>
              <template v-if="showGoldFinger">
              <tr><td>金手指金厚<span class="req">*</span></td><td :class="fieldBgClass('goldFingerThickness')"><el-autocomplete v-model="form.goldFingerThickness" :fetch-suggestions="queryGoldFingerThickness" size="large" style="width:100%" placeholder="输入搜索金手指金厚" clearable @select="(item: any) => { form.goldFingerThickness = item.value }"><template #default="{ item }"><div class="autocomplete-item">{{ item.value }} um</div></template></el-autocomplete><span class="unit">um</span></td><td class="td-src"><span :class="sourceClass('goldFingerThickness')">{{ sourceLabel('goldFingerThickness') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('goldFingerThickness')" class="btn-view graphic" @click="handleViewClick('goldFingerThickness')">图形</button><button v-if="showDocBtn('goldFingerThickness')" class="btn-view doc" @click="handleViewClick('goldFingerThickness')">加工文档</button></td></tr>
              <tr><td>倒角角度<span class="req">*</span></td><td :class="fieldBgClass('goldFingerChamferAngle')"><el-select v-model="form.goldFingerChamferAngle" size="large" style="width:100%"><el-option v-for="v in opts.goldFingerChamferAngle" :key="v" :label="v" :value="v" /></el-select></td><td class="td-src"><span :class="sourceClass('goldFingerChamferAngle')">{{ sourceLabel('goldFingerChamferAngle') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('goldFingerChamferAngle')" class="btn-view graphic" @click="handleViewClick('goldFingerChamferAngle')">图形</button><button v-if="showDocBtn('goldFingerChamferAngle')" class="btn-view doc" @click="handleViewClick('goldFingerChamferAngle')">加工文档</button></td></tr>
              <tr><td>倒角深度</td><td :class="fieldBgClass('goldFingerChamferDepth')"><el-input-number :controls="false" v-model="form.goldFingerChamferDepth" :min="0" :max="10" :precision="2" size="large" style="width:100%" /><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('goldFingerChamferDepth')">{{ sourceLabel('goldFingerChamferDepth') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('goldFingerChamferDepth')" class="btn-view graphic" @click="handleViewClick('goldFingerChamferDepth')">图形</button><button v-if="showDocBtn('goldFingerChamferDepth')" class="btn-view doc" @click="handleViewClick('goldFingerChamferDepth')">加工文档</button></td></tr>
              <tr><td>金手指倒角余厚</td><td :class="fieldBgClass('goldFingerChamferRemaining')"><el-input-number :controls="false" v-model="form.goldFingerChamferRemaining" :min="0" :max="10" :precision="2" size="large" style="width:100%" /><span class="unit">mm</span></td><td class="td-src"><span :class="sourceClass('goldFingerChamferRemaining')">{{ sourceLabel('goldFingerChamferRemaining') }}</span></td><td class="td-view"><button v-if="showGraphicBtn('goldFingerChamferRemaining')" class="btn-view graphic" @click="handleViewClick('goldFingerChamferRemaining')">图形</button><button v-if="showDocBtn('goldFingerChamferRemaining')" class="btn-view doc" @click="handleViewClick('goldFingerChamferRemaining')">加工文档</button></td></tr>
              </template>
          </template>
</template>
